# Site settings
title: PiMD
subtitle: Pi (Instruction) Multiple Data
author: Patrick Koenig & Nate Horan
email: pkoenig10@gmail.com
description: "Write a description here."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Patrick Koenig, Nate Horan

# Build settings
markdown: kramdown
permalink: pretty
